#!/usr/bin/perl

use warnings;
use strict;

my $filename = "AE_quads.obj";
open(OBJ, "$filename");
my $i = 1;

sub parse_obj_line {
  my ($line) = @_;
  my @l;
  @l = split /\s+/, $line;
  print "$l[0], $l[1], $l[2], $l[3]\n"; 
}

while(<OBJ>) {
  if(/^v/) {
    print "$i: ";
    parse_obj_line($_);
    $i++;
  }
}



